<?xml version="1.0"?>


<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Robot constants and properties -->
	<xacro:include filename="$(find ddr_pkg)/urdf/properties.xacro" />
	<!-- Import Rviz colors -->
	<xacro:include filename="$(find ddr_pkg)/urdf/materials.xacro" />
	<!-- Gazebo aspects of the robot -->
	<xacro:include filename="$(find ddr_pkg)/urdf/my_ddr.gazebo" />
	<!-- Inertia matrices -->
	<xacro:include filename="$(find ddr_pkg)/urdf/macros.xacro" />
	<!-- Sensor models-->
	<xacro:include filename="$(find ddr_pkg)/urdf/sensors.xacro" />

	<!-- Used for fixing robot to Gazebo 'chassis' -->
	<link name="base_footprint" />

	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="chassis"/>
	</joint>


	<link name='chassis'>

		<collision> 
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
			<geometry> 
				<mesh filename="package://ddr_pkg/meshes/chassis.dae" />
			</geometry>
			<material name="blue"/> 
		</collision>

		<visual> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<geometry>  
				<mesh filename="package://ddr_pkg/meshes/chassis.dae" />
			</geometry> 
			<material name="blue"/>
		</visual>

		<inertial> 
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
			<mass value="${chassisMass}"/> 
			<xacro:box_inertia 
				m="${chassisMass}" 
				x="${chassisLength}" 
				y="${chassisWidth}" 
				z="${chassisHeight}"/>
		</inertial>

	</link>


	<joint name="caster_joint" type="fixed">
		<parent link="chassis"/>
		<child link="caster_wheel"/>
	</joint>


	<link name="caster_wheel">

		<collision>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://ddr_pkg/meshes/caster_wheel.dae" />
	  		</geometry>
		</collision>

		<visual> 
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://ddr_pkg/meshes/caster_wheel.dae" />
			</geometry>
		</visual>

		<inertial>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<mass value="${casterMass}"/>
			<xacro:sphere_inertia 
				m="${casterMass}" 
				r="${casterRadius}"/>
		</inertial>

	</link>


	<xacro:wheel lr="left" tY="-1"/>
	<xacro:wheel lr="right" tY="1"/>

</robot>
